# Generated by Django 4.1.4 on 2022-12-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='room_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotdesk.room'),
        ),
    ]
