# Generated by Django 4.1.4 on 2023-01-23 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_layout',
            field=models.ImageField(default=None, upload_to='room_layout'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
