# Generated by Django 4.1.4 on 2022-12-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0002_alter_desk_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='desk_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
