# Generated by Django 4.1.4 on 2023-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0002_room_room_layout_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_layout',
            field=models.ImageField(blank=True, default=None, upload_to='room_layout'),
        ),
    ]
