# Generated by Django 4.1.4 on 2022-12-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0003_remove_desk_desk_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desk',
            old_name='room_id',
            new_name='room',
        ),
    ]
